version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: projeto_tcc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_DATABASE: projeto_tcc
      MYSQL_USER: user_projeto_tcc
      MYSQL_PASSWORD: user123
    ports:
      - '9990:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
